### ISSUE TITLE
Does this repo support any R Shiny app without modification against the app?

### ISSUE THREAD

**Issue by fishfree** [ARCLeeds/oauth2-proxy-shiny#3]
The shiny-server Dockerfile and [script ](https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_shiny_server.sh) seem having no packages related to OAuth, so I'm not sure this repo can support any R Shiny app without modification against the app even the app has no user authentication mechanism.

**Comment by Sparrow0hawk** [comment]
Hi @fishfree, the code here was looking at using [OAuth2-proxy](https://oauth2-proxy.github.io/oauth2-proxy/) as a proxy that runs in front of a Shiny app. OAuth2-proxy handles the OAuth flow to authenticate a user and can be configured using a text file of authorized users emails. Once a user authenticates with an OAuth provider (such as GitHub) OAuth2-proxy checks they are in the authorized users file and forwards their request to the Shiny app. This means the application doesn't need to know about OAuth at all which can be useful for restricting access to a dashboard or similar.

**Comment by fishfree** [comment]
Thank you very much! So, it does!
